package com.techtechnicworld.smart_quiz.services;

import com.techtechnicworld.smart_quiz.dto.*;
import com.techtechnicworld.smart_quiz.entities.Question;
import com.techtechnicworld.smart_quiz.entities.QuestionOption;
import com.techtechnicworld.smart_quiz.entities.Quiz;
import com.techtechnicworld.smart_quiz.entities.User;
import com.techtechnicworld.smart_quiz.enums.QuizStatus;
import com.techtechnicworld.smart_quiz.exceptions.QuizNotFoundException;
import com.techtechnicworld.smart_quiz.repository.QuestionRepository;
import com.techtechnicworld.smart_quiz.repository.QuizRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class QuizService {

    private final QuizRepository quizRepository;
    private final QuestionRepository questionRepository;

    // For regular users - only published quizzes, or filter by status
    public List<QuizResponseDto> getAllQuizzes(String status) {
        if (status != null && status.equalsIgnoreCase("ALL")) {
            return quizRepository.findAllByDeletedFalseOrderByCreatedAtDesc().stream()
                    .map(this::toQuizResponseDto)
                    .collect(Collectors.toList());
        }

        QuizStatus quizStatus = QuizStatus.PUBLISHED;
        if (status != null && !status.isEmpty()) {
            try {
                quizStatus = QuizStatus.valueOf(status.toUpperCase());
            } catch (IllegalArgumentException e) {
                // Default to PUBLISHED if invalid status
            }
        }

        return quizRepository.findByStatusAndDeletedFalseOrderByCreatedAtDesc(quizStatus).stream()
                .map(this::toQuizResponseDto)
                .collect(Collectors.toList());
    }

    // For admin - all quizzes
    public List<QuizResponseDto> getAllQuizzesForAdmin() {
        return quizRepository.findAllByDeletedFalseOrderByCreatedAtDesc().stream()
                .map(this::toQuizResponseDto)
                .collect(Collectors.toList());
    }

    public QuizResponseDto getQuizById(Long id) {
        Quiz quiz = quizRepository.findById(id)
                .orElseThrow(() -> new QuizNotFoundException("QUIZ_NOT_FOUND"));
        return toQuizResponseDto(quiz);
    }

    @Transactional
    public QuizResponseDto createQuiz(QuizRequestDto request, User admin) {
        QuizStatus status = request.getStatus() != null
                ? QuizStatus.valueOf(request.getStatus())
                : QuizStatus.DRAFT;

        Quiz quiz = Quiz.builder()
                .title(request.getTitle())
                .description(request.getDescription())
                .timePerQuestion(request.getTimePerQuestion())
                .status(status)
                .createdBy(admin)
                .build();

        quiz = quizRepository.save(quiz);
        return toQuizResponseDto(quiz);
    }

    @Transactional
    public QuizResponseDto updateQuiz(Long id, QuizRequestDto request) {
        Quiz quiz = quizRepository.findById(id)
                .orElseThrow(() -> new QuizNotFoundException("QUIZ_NOT_FOUND"));

        quiz.setTitle(request.getTitle());
        quiz.setDescription(request.getDescription());
        quiz.setTimePerQuestion(request.getTimePerQuestion());
        if (request.getStatus() != null) {
            quiz.setStatus(QuizStatus.valueOf(request.getStatus()));
        }

        quiz = quizRepository.save(quiz);
        return toQuizResponseDto(quiz);
    }

    @Transactional
    public void deleteQuiz(Long id) {
        Quiz quiz = quizRepository.findById(id)
                .orElseThrow(() -> new QuizNotFoundException("QUIZ_NOT_FOUND"));
        quiz.setDeleted(true);
        quizRepository.save(quiz);
    }

    @Transactional
    public QuestionResponseDto addQuestion(Long quizId, QuestionRequestDto request) {
        Quiz quiz = quizRepository.findById(quizId)
                .orElseThrow(() -> new QuizNotFoundException("QUIZ_NOT_FOUND"));

        Question question = Question.builder()
                .questionText(request.getQuestionText())
                .questionOrder(request.getQuestionOrder())
                .quiz(quiz)
                .build();

        // Build options with uniqueInsertId (generated by frontend or @PrePersist)
        List<QuestionOption> options = request.getOptions().stream()
                .map(opt -> QuestionOption.builder()
                        .uniqueInsertId(opt.getUniqueInsertId())
                        .optionText(opt.getOptionText())
                        .question(question)
                        .build())
                .collect(Collectors.toList());

        question.setOptions(options);
        Question savedQuestion = questionRepository.save(question);

        // Use correctOptionIds directly (frontend sends option IDs)
        if (request.getCorrectOptionIds() != null && !request.getCorrectOptionIds().isEmpty()) {
            savedQuestion.setCorrectOptionIdsList(request.getCorrectOptionIds());
            savedQuestion = questionRepository.save(savedQuestion);
        }

        return toQuestionResponseDto(savedQuestion);
    }

    @Transactional
    public QuestionResponseDto updateQuestion(Long questionId, QuestionRequestDto request) {
        Question existingQuestion = questionRepository.findById(questionId)
                .orElseThrow(() -> new QuizNotFoundException("QUESTION_NOT_FOUND"));

        existingQuestion.setQuestionText(request.getQuestionText());
        existingQuestion.setQuestionOrder(request.getQuestionOrder());

        // Build map for matching by ID
        Map<Long, QuestionOption> existingOptionsById = existingQuestion.getOptions().stream()
                .collect(Collectors.toMap(QuestionOption::getId, opt -> opt));

        // Clear existing options
        existingQuestion.getOptions().clear();

        List<QuestionOption> options = request.getOptions().stream()
                .map(opt -> {
                    // If option has an ID and exists in database, update it
                    if (opt.getId() != null && existingOptionsById.containsKey(opt.getId())) {
                        QuestionOption existing = existingOptionsById.get(opt.getId());
                        existing.setOptionText(opt.getOptionText());
                        return existing;
                    } else {
                        // New option
                        return QuestionOption.builder()
                                .optionText(opt.getOptionText())
                                .question(existingQuestion)
                                .build();
                    }
                })
                .toList();
        existingQuestion.getOptions().addAll(options);

        Question savedQuestion = questionRepository.save(existingQuestion);

        // Use correctOptionIds directly from request
        List<Long> correctOptionIds = request.getCorrectOptionIds();
        if (correctOptionIds != null && !correctOptionIds.isEmpty()) {
            savedQuestion.setCorrectOptionIdsList(correctOptionIds);
            savedQuestion = questionRepository.save(savedQuestion);
        }

        return toQuestionResponseDto(savedQuestion);
    }

    @Transactional
    public void deleteQuestion(Long questionId) {
        Question question = questionRepository.findById(questionId)
                .orElseThrow(() -> new QuizNotFoundException("QUESTION_NOT_FOUND"));

        int deletedOrder = question.getQuestionOrder();
        Long quizId = question.getQuiz().getId();
        question.setDeleted(true);
        questionRepository.save(question);

        // Re-sequence questionOrder for remaining questions
        List<Question> remaining = questionRepository.findByQuizIdAndDeletedFalseOrderByQuestionOrderAsc(quizId);
        for (int i = 0; i < remaining.size(); i++) {
            remaining.get(i).setQuestionOrder(i + 1);
        }
        questionRepository.saveAll(remaining);
    }

    public Page<QuestionResponseDto> getQuestionsByQuiz(Long quizId, int page, int size) {
        if (!quizRepository.existsById(quizId)) {
            throw new QuizNotFoundException("QUIZ_NOT_FOUND");
        }
        return questionRepository.findByQuizIdAndDeletedFalseOrderByQuestionOrderAsc(quizId, PageRequest.of(page, size))
                .map(this::toQuestionResponseDto);
    }

    // Get all questions for a quiz (no pagination) - for admin
    public List<QuestionResponseDto> getAllQuestionsByQuiz(Long quizId) {
        if (!quizRepository.existsById(quizId)) {
            throw new QuizNotFoundException("QUIZ_NOT_FOUND");
        }
        return questionRepository.findByQuizIdAndDeletedFalseOrderByQuestionOrderAsc(quizId).stream()
                .map(this::toQuestionResponseDto)
                .collect(Collectors.toList());
    }

    private QuizResponseDto toQuizResponseDto(Quiz quiz) {
        int activeQuestions = (int) quiz.getQuestions().stream()
                .filter(q -> !Boolean.TRUE.equals(q.getDeleted()))
                .count();
        return QuizResponseDto.builder()
                .id(quiz.getId())
                .title(quiz.getTitle())
                .description(quiz.getDescription())
                .timePerQuestion(quiz.getTimePerQuestion())
                .totalQuestions(activeQuestions)
                .createdBy(quiz.getCreatedBy().getName())
                .status(quiz.getStatus().name())
                .createdAt(quiz.getCreatedAt())
                .build();
    }

    private QuestionResponseDto toQuestionResponseDto(Question question) {
        List<QuestionResponseDto.OptionDto> optionDtos = question.getOptions().stream()
                .filter(opt -> !Boolean.TRUE.equals(opt.getDeleted()))
                .map(opt -> QuestionResponseDto.OptionDto.builder()
                        .id(opt.getId())
                        .uniqueInsertId(opt.getUniqueInsertId())
                        .optionText(opt.getOptionText())
                        .build())
                .toList();

        return QuestionResponseDto.builder()
                .id(question.getId())
                .questionText(question.getQuestionText())
                .questionOrder(question.getQuestionOrder())
                .correctOptionIds(question.getCorrectOptionIdsList())
                .options(optionDtos)
                .build();
    }
}
